# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bcac925ce8a5cd575db86da5a17f4ce9c29d645c2193305e5eddf8a6ab78be4a78021d4dff71d847f3806e58af4395df35007afa03e71be201bcc383be01d12

test:
  secret_key_base: 8f8fd6666b449401dfb1266e5ec4ba31b7a267c594d1d037fa48756614fcb9ba10ddb9877d195bef26c2cad9c161011ed69e24651f5c9404515e32de2d06a613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
